### ISSUE TITLE
Not installing on iojs 1.2

### ISSUE THREAD

**Issue by megastef** [bretcope/node-gc-profiler#3]
After installation of iojs 1.2  (https://iojs.org/en/index.html) and 

   npm install gc-profiler 

I get this errors:

<code>
> gc-profiler@1.1.0 install /Users/stefan/node_modules/gc-profiler
> node-gyp rebuild
child_process: customFds option is deprecated, use stdio instead.
  CXX(target) Release/obj.target/GcProfiler/src/GcProfiler.o
In file included from ../src/GcProfiler.cc:2:
../src/../node_modules/nan/nan.h:481:19: error: no type named
      'ExternalAsciiStringResource' in 'v8::String'; did you mean
      'ExternalStringResource'?
      v8::String::ExternalAsciiStringResource *resource) {
      ~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~
                  ExternalStringResource
/Users/stefan/.node-gyp/1.2.0/deps/v8/include/v8.h:2016:19: note: 
      'ExternalStringResource' declared here
  class V8_EXPORT ExternalStringResource
                  ^
In file included from ../src/GcProfiler.cc:2:
../src/../node_modules/nan/nan.h:480:36: error: redefinition of 'NanNew'
  NAN_INLINE v8::Local<v8::String> NanNew(
                                   ^
../src/../node_modules/nan/nan.h:475:36: note: previous definition is here
  NAN_INLINE v8::Local<v8::String> NanNew(
                                   ^
../src/../node_modules/nan/nan.h:2114:12: error: no member named
      'IsExternalAscii' in 'v8::String'; did you mean 'IsExternal'?
  if (str->IsExternalAscii()) {
           ^~~~~~~~~~~~~~~
           IsExternal
/Users/stefan/.node-gyp/1.2.0/deps/v8/include/v8.h:1980:8: note: 'IsExternal'
      declared here
  bool IsExternal() const;
       ^
In file included from ../src/GcProfiler.cc:2:
../src/../node_modules/nan/nan.h:2115:23: error: no type named
      'ExternalAsciiStringResource' in 'v8::String'; did you mean
      'ExternalStringResource'?
    const v8::String::ExternalAsciiStringResource* ext;
          ~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~
                      ExternalStringResource
/Users/stefan/.node-gyp/1.2.0/deps/v8/include/v8.h:2016:19: note: 
      'ExternalStringResource' declared here
  class V8_EXPORT ExternalStringResource
                  ^
In file included from ../src/GcProfiler.cc:2:
../src/../node_modules/nan/nan.h:2116:16: error: no member named
      'GetExternalAsciiStringResource' in 'v8::String'; did you mean
      'GetExternalOneByteStringResource'?
    ext = str->GetExternalAsciiStringResource();
               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
               GetExternalOneByteStringResource
/Users/stefan/.node-gyp/1.2.0/deps/v8/include/v8.h:2083:40: note: 
      'GetExternalOneByteStringResource' declared here
  const ExternalOneByteStringResource* GetExternalOneByteStringResource() const;
                                       ^
In file included from ../src/GcProfiler.cc:2:
../src/../node_modules/nan/nan.h:2116:9: error: assigning to 'const
      v8::String::ExternalStringResource *' from incompatible type 'const
      v8::String::ExternalOneByteStringResource *'
    ext = str->GetExternalAsciiStringResource();
        ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../src/../node_modules/nan/nan.h:2117:11: error: assigning to 'const char *' from
      incompatible type 'const uint16_t *' (aka 'const unsigned short *')
    *data = ext->data();
          ^ ~~~~~~~~~~~
7 errors generated.
make: *** [Release/obj.target/GcProfiler/src/GcProfiler.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
</code>

Pls. check also latest changes in nan.  https://github.com/rvagg/nan
I wonder about this entry in package.json as well:
"dependencies": {
    "nan": "git+https://github.com/rvagg/nan.git#df2cdbcc4869af5ed1e29e2e6d5aeed9ad5a3f41"
  }

**Comment by bretcope** [comment]
The reason for the reference to the specific nan commit was because I needed some changes which weren't in any release yet, but they probably are now. I haven't checked in a long time.

I'll take a look at whether this compiles on node 0.12 correctly, but I have no interest in supporting io.js. If you'd like to submit a PR with a fix, I'd be happy to review it.

**Comment by megastef** [comment]
1) I use it on 0.12 so far without any issues. 
2) On a local test it did well by using NAN 1.6.2. I might do a pull request for it - if this also solves iojs issue. 
3) On windows it failed because "qos.h" could not be found using VC++ 2013 (seems to be an issue with the C++ ENV there - probably my mistake -  Any tip for Windows?, I'm there a Noop (after not using it for a few years ...).

**Comment by megastef** [comment]
Made a pull request using NAN 1.6.2 - only version changes in package.json. Was running on node 0.12 and iojs 1.2

**Comment by megastef** [comment]
Compilation and running example.js on >0.10, 0.11, 0.12, 1.2 (iojs) on Mac OS X -  using the pull request https://github.com/bretcope/node-gc-profiler/pull/4. Looks good but old version v0.8.28 fails. If you want to try with your packages  
```
  npm install ny -g
  for version in  0.10.35 0.10.36  0.11.16 0.12 1.2
  do
      ny $version
      node --version
      npm install
      npm test
  done
```

**Comment by bretcope** [comment]
I'll give it a try on Windows. I'm not sure what qos.h is.

**Comment by seti123** [comment]
Probably something missing on VC++ 2013, Win 8.1 on my VM - Thats the error on windows:
C:\Program Files (x86)\Windows Kits\8.1\Include\um\winsock2.h(882): fatal error
 C1083: Cannot open include file: 'qos.h':

**Comment by bretcope** [comment]
It builds fine for me on Windows 8.1, so it seems you are correct that there's something wrong or missing with your setup. If you care about debugging it, you'll need to post the whole output and we'll see if anything else gives clues. If you were only concerned about testing it on windows, then I wouldn't worry about it.

**Comment by megastef** [comment]
Thx  a lot - it was about testing on windows. But happy that all the new node versions work!
